language: node_js
node_js:
  - "10"
  - "12"
  - "14"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
<<<<<<< HEAD
   - npm test
=======
  - npm test
>>>>>>> b253987fb38a06aa01f8a97b34da114b1e98882d
